baseURL: www.omingale.in
languageCode: en-us
title: Om Ingale
theme: ["PaperMod"]

params:
  defaultTheme: auto
  disableThemeToggle: false

  homeInfoParams:
    Title: Hello!👋
    Content: |
      Welcome to my personal website.
      I'm a data engineer living in Mumbai, India. I have recently started this personal blog and will try to write more here.

      Here you can find all my socials and all things related to data.

  socialIcons:
    - name: "github"
      url: "https://github.com/omingale0707"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/omi7/"
    - name: "email"
      url: "mailto:omingale0707@gmail.com"

menus:
  main:
  - identifier: about
    name: About Me
    pageRef: about/
    weight: 1

caches:
  images:
    dir: :cacheDir/images